version: '3.8'

services:
  go-app:
    container_name: tc-go-app
    build:
      context: .
      target: dev
    env_file:
      - .env
    ports:
      - "2345:2345"
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - tacans

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - tacans

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tacans

volumes:
  postgres_data:

networks:
  tacans:
