version: '3.8'

services:
  go-app:
    container_name: tc-go-app
    build:
      context: .
      target: dev
    env_file:
      - local.env
    ports:
      - "2345:2345"  # Debugger port
      - "8080:8080"  # App port
    volumes:
      - .:/app
    networks:
      - tacans

networks:
  tacans:
